spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb_first?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 198251
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8181